spring.application.name=hr-managment-system
spring.datasource.url=jdbc:postgresql://localhost:5432/hr-management
spring.datasource.username=postgres
spring.datasource.password=seng12
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true